name: posting-by-issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types:
      - labeled

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  add-comment:
    if: github.event.label.name == 'release'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name : Add ssh key
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: View isue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      - name : Rename file
        run: echo "FILE_NAME=$(echo ${{ github.event.issue.title }} | tr ' ' -)" >> $GITHUB_ENV

      - name : Write file and push to repo
        run:  echo "${{ github.event.issue.body }}" > _posts/"${{ env.FILE_NAME }}".md
              
      - name : Commit and push
        run: |
          git config --global user.name "0leaf"
          git config --global user.email "0leaf.dev@gmail.com"
          git add .; git commit -m "Update ${{ github.event.issue.title }}.md"
          git push
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Post has been released! :sparkles:
      - uses: actions-ecosystem/action-remove-labels@v1
        # if: ${{ startsWith(github.event.comment.body, '/remove-labels') }}
        with:
          labels: release