name: posting-by-issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types:
      - labeled

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  add-comment:
    # post 파일 삭제 여부 판단
    # comment 정보 읽기

    # comment 파일 생성

    # 완료 comment 생성
    if: github.event.label.name == 'help-wanted'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name : Add ssh key
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: View isue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      - name : Write file and push to repo
        run: |
          echo "${{ github.event.issue.body }}" > _posts/daily/"${{ github.event.issue.title }}".md
      - name : Commit and push
        run: |
          git config --global user.name "0leaf"
          git config --global user.email "0leaf.dev@gmail.com"
          git add &lt;pathspec&gt; git commit -m "Update ${{ github.event.issue.title }}.md"
          git push
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
